points="example/points_structure1_fullstruct.csv"
materials="example/material_sample.csv"
natural_bcs="example/natural_structure1_fullstruct.csv"
numerical_bcs="example/numerical_structure1_fullstruct.csv"
profiles="example/profiles_structure1_fullstruct.csv"
elements="example/elements_structure1_fullstruct.csv"
silent=false
gravity=9.81
show_unsolved=true
show_deformed=true
deformation_scale=100
show_stresses=true
node_output_destination="some_file.csv"
element_output_destination="another_file.csv"
general_output_destination="misc.txt"
save_figs=true
fig_folder="."
